# Fix project warings
SoftwareEngineeringDaily/se-daily-iOS pull request #18
Opened 2017-10-07 00:02 UTC by justinctlam

* Set objc inference to be default as it inference is deprecated in Swift 4.
* Add @objc for variables and methods that require it as auto inference is deprecated.
* Fixed autolayout warning for PodcastCollectionViewCell as one of the
* Enable dwarf-with-dysm for debug build to remove warning

2017-10-07 00:47 UTC, themisterholliday requested changes
This is all perfect! One thing. The project needs to build in CocoaPods 1.3.1 not the beta. I think this is as easy as rolling back your CocoaPods version and doing `pod update`.

2017-10-09 04:28 UTC, justinctlam commented
Fix the CocoaPods versioning.

2017-10-09 04:43 UTC, themisterholliday approved these changes

2017-10-09 04:43 UTC, merged

2017-10-09 04:46 UTC, themisterholliday commented
HOT 🔥! Also this is the first merged PR for iOS so double points for this! Thanks!